# Generated by Django 3.0.6 on 2020-05-29 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=500)),
                ('dateApplied', models.DateField(default=datetime.datetime(2020, 5, 29, 22, 48, 46, 938778))),
            ],
        ),
    ]
