# Generated by Django 3.0.6 on 2020-05-29 22:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dateApplied',
            field=models.DateField(default=datetime.datetime(2020, 5, 29, 22, 50, 11, 307963, tzinfo=utc)),
        ),
    ]
