# Generated by Django 3.0.6 on 2020-06-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0005_auto_20200601_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='reminderDate',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
